<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI02X0Np\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI02X0Np/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI02X0Np.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI02X0Np\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerI02X0Np\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'I02X0Np',
    'container.build_id' => '823c382b',
    'container.build_time' => 1578560593,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI02X0Np');
